### ISSUE TITLE
Doesn't compile in Visual Studio 2013

### ISSUE THREAD

**Issue by 1vanK** [LucKeyProductions/heXon#1]
error C2039: Length: is not a member of the "Urho3D::Vector<double>"

mastercontrol.h(120): error C3861: Cycle: identifier not found

arenaedge.cpp(44): error C2660: Urho3D::Node::SetPosition: need Vecto3(x, y, z)

arenaedge.cpp(79): error C3861: Distance: identifier not found

tilemaster.h(76): error C2039: Length: is not a member of the "Urho3D::Vector<U>"

enemy.cpp(49): error C2668: Urho3D::Max: an ambiguous call to overloaded function
MathDefs.h(120): "int Urho3D::Max(int,int)" or
MathDefs.h(66): "float Urho3D::Max(float,float)"

and another 200+ errors :(

**Comment by Modanung** [comment]
This is because of some modifications I made to the engine locally. Will fix this. These issues are also mentioned and (in part) fixed in [this](http://urho3d.prophpbb.com/topic1192.html) topic.

**Comment by Modanung** [comment]
Should be fixed.

**Comment by Modanung** [comment]
Fixed

**Comment by 1vanK** [comment]
259 errors with latest version engine

**Comment by Modanung** [comment]
Could you share the error log?

**Comment by 1vanK** [comment]
Full building log https://drive.google.com/open?id=0B_XuF2wRVpw4cWNrS1JyMGVlbE0
Sorry, it's russian version of VS

**Comment by Modanung** [comment]
Have you tried compiling Urho3D on it's own, or a different Urho3D project?
It seems like these errors are not related to heXon.

**Comment by 1vanK** [comment]
I'm using the standard method http://urho3d.github.io/documentation/1.4/_using_library.html

**Comment by 1vanK** [comment]
mastercontrol.h: #include <helper.h> -> #include "helper.h"

**Comment by 1vanK** [comment]
uint not defined

**Comment by 1vanK** [comment]
mastercontrol.h
eroor in string float Sine(float x) { return sine_[(int)round(sine_.Size() * heXon::Cycle(x/M_PI, 0.0f, 1.0f))%sine_.Size()]; } 
not defined Cycle(double, float, float)

**Comment by Modanung** [comment]
The Cycle error should have been fixed a few commits ago.
I'll give you the honors of closing the issue.

**Comment by Modanung** [comment]
Was fixed by [pull request](https://github.com/LucKeyProductions/heXon/pull/2).
