### ISSUE TITLE
some files under Resource/Models are symlinks

### ISSUE THREAD

**Issue by yushli** [LucKeyProductions/heXon#4]

**Comment by Modanung** [comment]
Darn. I thought it would upload the linked-to file.

**Comment by Modanung** [comment]
Now I know about hard links. :)

**Comment by yushli** [comment]
thanks for the quick response. 
heXon is a cool game. Thank you for sharing it! Hope to see more improvements.

**Comment by Modanung** [comment]
Glad you like it. :)
